# Generated by Django 4.0.4 on 2022-06-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreContacto', models.CharField(max_length=200, verbose_name='Nombre del contacto')),
                ('correoContacto', models.CharField(max_length=200, verbose_name='Correo del contacto')),
                ('comentarioContacto', models.TextField(max_length=1000, verbose_name='Comentario del contacto ')),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('codigoProducto', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Codigo del producto')),
                ('nombreProducto', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcionProducto', models.TextField(max_length=1000, verbose_name='Descripcion del producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio del producto')),
            ],
        ),
        migrations.CreateModel(
            name='registro',
            fields=[
                ('nombreUsuario', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Nombre del usuario')),
                ('correoUsuario', models.CharField(max_length=100, verbose_name='Correo del usuario')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellidoPaterno', models.CharField(max_length=50, verbose_name='Apellido paterno')),
                ('apellidoMaterno', models.CharField(max_length=50, verbose_name='Apellido materno')),
                ('direccion', models.TextField(max_length=500, verbose_name='Direccion')),
                ('passwordUsuario', models.CharField(max_length=200, verbose_name='Contraseña del usuario')),
            ],
        ),
    ]
