# Generated by Django 4.0.4 on 2022-06-10 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagenProducto',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='Imagen del producto'),
            preserve_default=False,
        ),
    ]
