# Generated by Django 4.0.4 on 2022-06-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='direccion',
            field=models.TextField(max_length=100, verbose_name='Direccion'),
        ),
    ]
