# Generated by Django 4.0.4 on 2022-06-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_registro_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Direccion'),
        ),
    ]
