# Generated by Django 4.0.4 on 2022-06-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_registro_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcionProducto',
            field=models.CharField(max_length=500, verbose_name='Descripcion del producto'),
        ),
    ]
