# Generated by Django 4.0.4 on 2022-06-15 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_registro_options_alter_registro_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro',
            options={},
        ),
        migrations.AlterModelManagers(
            name='registro',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='registro',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='user_permissions',
        ),
    ]
